# Generated by Django 3.1.2 on 2020-10-20 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pets.pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('Dog', 'dog'), ('Cat', 'cat'), ('Parrot', 'parrot'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=7),
        ),
    ]
