# Generated by Django 3.1.2 on 2020-10-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20201020_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='test',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
