# Generated by Django 3.1.2 on 2020-11-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20201119_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='image_url',
            new_name='image',
        ),
    ]
